"""fix models

Revision ID: 1ced45557380
Revises: 4b24e5bed649
Create Date: 2025-06-18 22:15:28.993005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ced45557380'
down_revision: Union[str, Sequence[str], None] = '4b24e5bed649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('tweet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'tweets', ['tweet_id'], ['id'])
    op.create_unique_constraint('follow_uc', 'follows', ['follower_id', 'follow_on_id'])
    op.create_unique_constraint('like_uc', 'likes', ['tweet_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_uc', 'likes', type_='unique')
    op.drop_constraint('follow_uc', 'follows', type_='unique')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'tweet_id')
    # ### end Alembic commands ###
