"""Remove tweet_id in attachments

Revision ID: 4b24e5bed649
Revises: 4433a04153f3
Create Date: 2025-06-18 19:06:25.045051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b24e5bed649'
down_revision: Union[str, Sequence[str], None] = '4433a04153f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_tweet_id_fkey'), 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'tweet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('tweet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attachments_tweet_id_fkey'), 'attachments', 'tweets', ['tweet_id'], ['id'])
    # ### end Alembic commands ###
