services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://admin:admin@db:5432/twitter_db"
    networks:
      - app_network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=twitter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d twitter_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

volumes:
  postgres_data:
  postgres_logs:

networks:
  app_network:
    driver: bridge